parameters:
    locale: en

    secret: ThisTokenIsNotSoSecretChangeIt

    database_driver: pdo_sqlite
    database_path: %kernel.root_dir%/app.sqlite

    phpcr_backend:
        type: doctrinedbal
        connection: doctrine.dbal.default_connection
    phpcr_workspace: default
    phpcr_user: admin
    phpcr_pass: admin
